flags:
  synquid:
    synquid: true
packages:
  - '.'
resolver: lts-15.3
extra-deps:
  - z3-4.3.1
extra-include-dirs:
 - /home/michael/sandbox/z3/src/api
extra-lib-dirs:
 - /home/michael/sandbox/z3/build
